<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="pdict.css" type="text/css"?>
<!DOCTYPE particles [


	<!ELEMENT particles (license, notice, gyou*)>
	<!ELEMENT gyou (entry*)>

	<!-- license structure -->
	<!ELEMENT license (header, body)>
	<!ELEMENT header (line*)>
	<!ELEMENT body (para*,line*)*>

	<!-- notice structure -->
	<!ELEMENT notice (para*)>
	<!ELEMENT para (#PCDATA)>
	<!ELEMENT line (#PCDATA)>

	<!-- row marker -->
	<!ELEMENT gyou (#PCDATA)>
	<!ATTLIST gyou kana CDATA #REQUIRED>

	<!-- entry structure -->
	<!ELEMENT entry (particle, literary*, compound?, use, description, roles?, contrast*, see*, example*)>
	<!ATTLIST entry id CDATA #REQUIRED>

	<!ELEMENT particle (#PCDATA)>
	<!ELEMENT literary (#PCDATA)>
	<!ELEMENT compound (#PCDATA)>
	<!ELEMENT use (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT roles (role*)>
	<!ELEMENT role (#PCDATA)>

	<!ELEMENT contrast (#PCDATA)>
	<!ATTLIST contrast id CDATA #IMPLIED>

	<!ELEMENT see (#PCDATA)>
	<!ATTLIST see id CDATA #IMPLIED>
	
		<!-- example structure -->
		<!ELEMENT example (phrase, phrase, explanation)>
		<!ATTLIST example role CDATA #IMPLIED>
		<!ELEMENT phrase (CDATA,p*,ruby*)*>
		<!ATTLIST phrase lang CDATA #REQUIRED>
		<!ELEMENT explanation (#PCDATA)>
	
	<!-- particle highlight -->
	<!ELEMENT p (#PCDATA)>
	<!-- particle subordinate construction highlight -->
	<!ELEMENT s (#PCDATA)>
	
	<!-- simple ruby markup -->
	<!ELEMENT ruby (rb, rt)>
	<!ELEMENT rb (#PCDATA)>
	<!ELEMENT rt (#PCDATA)>

]>

<particles header="A Japanese mostly-suffix dictionary">

<!--
	一人だけでしました。　emphasizes the fact you were alone

	一人でやりました。 emphasizes the fact you did it on your own
-->

	<license>
		<header>
			<line>An XML Japanese mostly-suffix dictionary</line>
			<line>Composed and written by Michiel Kamermans</line>
			<line>(c) 2003-2007 Nihongoresources</line>
			<line>http://www.nihongoresources.com</line>
			<line>THIS FILE IS AT PRESENT STILL UNDER DEVELOPMENT AND SUBJECT TO CHANGE WITHOUT NOTICE</line>
		</header>

		<body>
			<para>This document is not released under the creative commons or GPL license, but under the following license:</para>
			<para><line>- You are not allowed to modify this document.</line>
			<line>- Consequently, you are only allowed to redistribute this document in unmodified form.</line>
			<line>- You may convert the data in this document to a different data format for either private or public polling.</line>
			<line>- You may, however, not redistribute the data as converted format.</line>
			<line>- When making parts of this data publically available, you will include this license text in some directly visible way (such as linking to a page
			with this license text, or verbatim copying it. Hiding it in html sourcecode or something that is not directly obvious does not fall under
			  "directly visible").</line></para>
			<para>In this license, redistribution is not the same as letting people view excerps such as when the data is used for instance on a searchable website</para>
			<para>You can always contact if you feel you need to break these agreements, so we can talk over the particulars.</para>
		</body>
	</license>

	<notice>
		<para><ruby><rb>始</rb><rt>はじ</rt></ruby>めに</para>

		<para>Whenever you see "noun phrase" or "verb phrase", these are used as grammatical terms, meaning they entail single nouns and single verbs.
		I tried to separate use (ie: how is the prefix/suffix/contraction used in a sentece) from description (ie: what does it actually do). Should you
		notice an unnecessary overlap in an entry, please contact me so that this document can be updated.</para>

		<para>Also, I use the term <ruby><rb>已然形</rb><rt>いぜんけい</rt></ruby> rather than <ruby><rb>仮定形</rb><rt>かていけい</rt></ruby>, mostly because
		the first is the grammatical name, and the second the colloquial name for this　base. Since this dictionary concerns grammar, it would be odd to use 
		仮定形 instead.</para>

		<para>You will see a lot of words in brackets in the example phrases. I used this styling to indicate contextually implied words that are not to be found
		in the Japanese sentence, but are required for a natural English translation. As always, personal pronouns are particularly fun: it doesn't matter
		which is used. Wherever you see one used, you can replace it with any other personal pronoun that fits the used case.</para>
		
		<para>There will be entries which concern classical helper verbs. In these cases you will see a list of bases, such as for た: [たろ・×・た・た・たら・×]. This
		list is organised in the same way as any other Japanese dictionary organises them: [未然形・連用形・終止形・連体形・已然形・命令形]. An × indicates there
		is no such form.</para>
		
		<para>You will need a browser that properly supports CSS2 (firefox, opera, netscape, safari) in order to "enjoy" the raw XML file; IE7 still does not support
		the rather important :before and :after pseudo-classes that this document uses for its field labels. If you are using IE for this document, please stop and
		either install the css2 fixes plugin for it (I have only been told this exists, you'll have to find it yourself), or install another browser alongside IE and be that
		bit more standards-adhering.</para>
	</notice>


	<!--
		The following list contains entries yet to be added:
		
		- かぎり
		- しだい
		- だけあって?
		- だけで?
		- だけに?
		- ばあい
		- まま (まんま)
		- わけ
		
	-->


	<gyou kana="あ"/>
	
	<entry id="1">
		<particle>い</particle>
		<use>sentence ending</use>
		<description>Used in highly assertive speech, often following sentence ending だ (plain copula), か (questioning) or わ (emphatic). Possibly regional.</description>
		<see id="42">だ+い</see>
		<see id="5">か+い</see>
		<see id="134">わ+い</see>
	</entry>

	<entry id="139">
		<particle>お</particle>
		<literary>御</literary>
		<use>noun prefix</use>
		<description>Honorifix prefix. Used (predominantly) for native Japanese words or words that use Japanse readings for their kanji.</description>
		<see id="140">ご</see>
		<see id="141">み</see>
		<example role="example">
			<phrase lang="jp"><s><p>お</p><ruby><rb>天気</rb><rt>てんき</rt></ruby></s>がいいですね。</phrase>
			<phrase lang="en">The weather is quite nice, isn't it?</phrase>
			<explanation>The word "weather", 天気, has been made honorific, making the sentence as a whole softer.</explanation>
		</example>
	</entry>



	<gyou kana="か"/>
	
	<entry id="2">
		<particle>か</particle>
		<use>連体形 suffix</use>
		<description>This particle marks a statement as being a questioning statement. Note this leads to more roles than just acting as question mark at the end of sentences.</description>
		<roles>
			<role>question mark</role>
			<role>logical "or"</role>
			<role>dubitative</role>
		</roles>
		<example role="question mark">
			<phrase lang="jp"> コンビニに<s><ruby><rb>行</rb><rt>い</rt></ruby>った<p>か</p></s>。</phrase>
			<phrase lang="en">Did you go to the convenience store?</phrase>
			<explanation>Without か, this phrase means "[I] went to the convenience store". The addition of か marks this as being in question instead.</explanation>
		</example>
		<example role="questioning">
			<phrase lang="jp"><s>しよう<p>か</p></s>と<ruby><rb>思</rb><rt>おも</rt></ruby>った</phrase>
			<phrase lang="en">I thought [about] whether I should do it.</phrase>
			<explanation>Here the subphrase しよう is made a questioning statement, making the thought "shall [I] do?" rather than "[I] shall do". Like
			in the previous example, the subphrase しよう is in question, which is then stated as someone's thought.</explanation>
		</example>
		<example role="natural or">
			<phrase lang="jp"><s>コーヒーにします<p>か</p></s>、<s>お<ruby><rb>茶</rb><rt>ちゃ</rt></ruby>にします<p>か</p></s>。</phrase>
			<phrase lang="en">Will you have coffee, or tea?</phrase>
			<explanation>This is the "natural" interpretation of the choice operator "or", where two (or more) options are given,
			and only one of these may be chosen. Note that while in English this is one sentence, in Japanese this is necessarily two
			sentences in succession. Decomposed this sentence reads "will you have [coffee] or [tea]", with the parts in brackets being
			individual choices.</explanation>
		</example>
		<example role="logical or">
			<phrase lang="jp"><s>コーヒー<p>か</p>お<ruby><rb>茶</rb><rt>ちゃ</rt></ruby></s>にします<p>か</p>。</phrase>
			<phrase lang="en">Will you have [some] coffee or tea?</phrase>
			<explanation>We see two "roles" of か here: the first is the "logical" interpration of "or", the second is what we would use a question
			mark for in English. Unlike the previous example the first か sets up a truth conditional, which is true if either coffee or tea or even both
			will be chosen. Unlike the previous example, which asks about which choice someone will go for, this question asks for a yes/no question.
			If answered yes, the speaker knows the listener will have any or all choices listed, and if no the speaker knows that none of the choices
			work. Decomposed this sentence reads "will you have [coffee or tea]" with the part in brackets being one thing, not distinct choices as
			such. </explanation>
		</example>
		<example role="generic interrogative answer">
			<phrase lang="jp"><s>いつ<p>か</p></s><ruby><rb>出</rb><rt>で</rt></ruby>ます。</phrase>
			<phrase lang="en">[It] will come out eventually.</phrase>
			<explanation>Normally いつ is a Japanese interrogative meaning "when". When affixed with か, all Japanese interrogatives turn into generic
			answers to these interrogatives: "when" becomes "some [unspecified] time", "where" becomes "some [unspecified] place", "what"
			becomes "some [unspecified] thing" and so forth.</explanation>
		</example>
	</entry>

	<entry id="3">
		<particle>が</particle>
		<use>noun/verb phrase suffix</use>
		<description>Marks the subject of a verbal clause. In some cases this may lead to が also leading to a perceived contrast in a sentence.</description>
		<contrast id="90">に</contrast>
		<contrast id="135">を</contrast>
		<example role="verb subject">
			<phrase lang="jp"><s><ruby><rb>母</rb><rt>かあ</rt></ruby>さん<p>が</p></s><ruby><rb>呼</rb><rt>よ</rt></ruby>んでたよ。</phrase>
			<phrase lang="en">Mother called you.</phrase>
			<explanation>In this sentence "mother" is the subject of the verb "call". Given the verb's meaning, this implies she's the one
			doing the calling, as what or who is called would be marked as direct object, which uses を in Japanese instead.</explanation>
		</example>
		<example role="verbal adjective subject">
			<phrase lang="jp"><s>それ<p>が</p></s><ruby><rb>好</rb><rt>す</rt></ruby>きです。</phrase>
			<phrase lang="en">I like that.</phrase>
			<explanation>Since verbal adjectives do not have direct objects (adjectives only describe aspects of something, they do not
			act upon somethings) the thing they apply to is marked a subject to it. In this case the Japanese adjective 好き attributes the
			property of being-liked to the subject それ, "that". Note that "I" is completely implied and could just as well be any other
			personal pronoun.</explanation>
		</example>
		<example role="weak contrast">
			<phrase lang="jp"><s>そう<ruby><rb>言</rb><rt>い</rt></ruby>った<p>が</p></s>、<ruby><rb>間違</rb><rt>まちが</rt></ruby>ってた。</phrase>
			<phrase lang="en">I said that (lit: thusly), but I was wrong.</phrase>
			<explanation>Here there is a weak contrast between the two statements. The second part is only a contrast to what the first part
			implies, rather than being a direct contrast. Essentially what we see here is that the entire phrase そう言った is the subject to the
			verb "being wrong".</explanation>
		</example>
		<example role="a special case">
			<phrase lang="jp"><s><ruby><rb>済</rb><rt>す</rt></ruby>みません<p>が</p></s>、<ruby><rb>通</rb><rt>とお</rt></ruby>してもらえませんか。</phrase>
			<phrase lang="en">Excuse me, could [I have] you let me through?</phrase>
			<explanation>For this example to make sense, it is required to know that すみません is not just an expression, but actually means something.
			Used in situations where a debt-relation is created (no matter how minor), this expression notes that after the situation has been resolved
			there will be a debt relation that prevails, rather than ending there and then (this debt by action has been at the basis of social interaction
			in Japanese culture throughout its history). Knowing this, the が in this example marks the expression as a "soft" subject; the "letting of
			someone through" is in this case fascilitated (though obviously not strictly speaking performed) by the expression. Usually example phrases
			of the kind "すみませんが、... " are explained as having が act as something different from the subject marker, but this is not quite true, it is
			merely a more subtle interpretation, made harder by the lack of such subtleties in English, which does not have explicit grammar markers but
			has to divide up the grammar in terms of roles. This example then not only explains the use of が in it, but also highlights the problem in
			explaining intrinsic differences between role-based and marker-based grammar explanation.</explanation>
		</example>
	</entry>

	<entry id="5">
		<particle>かい</particle>
		<compound>か+い</compound>
		<use>sentence ending</use>
		<description>A compound of か and い.</description>
		<see id="2">か</see>
		<see id="1">い</see>
		<example role="example">
			<phrase lang="jp"><s><ruby><rb>行</rb><rt>い</rt></ruby>くの<p>かい</p></s>。</phrase>
			<phrase lang="en">So: are you going?</phrase>
			<explanation>The addition of い to the questioning particle か greatly emphasises the whole phrase. Without it, the Japanese would be better
			translated as merely reading "are you going?".</explanation>
		</example>
	</entry>

	<entry id="6">
		<particle>かな</particle>
		<compound>か+な</compound>
		<use>sentence ending</use>
		<description>A compound of か and な.</description>
		<roles>
			<role>dubitative</role>
		</roles>
		<example role="example">
			<phrase lang="jp">これ、<s><ruby><rb>出来</rb><rt>でき</rt></ruby>る<p>かな</p></s>。</phrase>
			<phrase lang="en">I wonder if we can do this.</phrase>
			<explanation>Note that "do" here refers only to the physical act of doing, not to the expression "... can do ..." that in English implies questioning
			whether social responsibility should be taken. The role of かな as dubitative comes from the combination of a questioning statement paired with な,
			which marks a statement as being almost rhetoric in seeking agreement. The addition of な leads to the statement 出来るか, "can [we] do?" being
			posed as an agreement seeking question "do you think we can do" without the explicit "do you" part. In English we write that as a self-posing
			question "I wonder whether ...", but this is strictly speaking not what happens in Japanese. The Japanese question remains one that is asked
			in a half-expecting-agreement fashion when there are listeners present (In the case that there is no one else present, this is a normal example
			of someone talking to themselves).</explanation>
		</example>
	</entry>

	<entry id="7">
		<particle>がな</particle>
		<compound>が+な</compound>
		<use>sentence ending</use>		
		<description>A compound of が and な, expresses a hopefulness.</description>
		<example role="example">
			<phrase lang="jp"><ruby><rb>前回</rb><rt>ぜんかい</rt></ruby><ruby><rb>来</rb><rt>こ</rt></ruby>なくて、<ruby><rb>今回</rb><rt>こんかい</rt></ruby>は<s>みんなが<ruby><rb>来</rb><rt>き</rt></ruby>たらいい<p>がな</p></s>。</phrase>
			<phrase lang="en">Given the last time, it would be great if everyone showed up this time...</phrase>
			<explanation>From the sentence it should be obvious that it is highly unlikely that the event "everyone will come" will indeed transpire. As such,
			the addition of がな makes this more a hope than anything.</explanation>
		</example>
	</entry>

	<entry id="8">
		<particle>かなあ</particle>
		<compound>か+なあ</compound>
		<use>sentence ending</use>
		<description>A compound of か and なあ.</description>
		<roles>
			<role>strong rhetorical statement</role>
		</roles>
		<see id="6">かな</see>
	</entry>

	<entry id="9">
		<particle>がなあ</particle>
		<compound>が+なあ</compound>
		<use>sentence ending</use>
		<description>A compound of が and なあ, expresses strong hopefulness</description>
		<see id="7">がな</see>
	</entry>

	<entry id="10">
		<particle>がてら</particle>
		<use>noun/verb 連用形 suffix</use>
		<description>Marks a "base" event during which a shorter event takes place.</description>
		<roles>
			<role>while</role>
			<role>during</role>
		</roles>
		<contrast id="84">ながら</contrast>
		<example role="incidental duration">
			<phrase lang="jp"><s><ruby><rb>散歩</rb><rt>さんぽ</rt></ruby><p>がてら</p></s><ruby><rb>買</rb><rt>か</rt></ruby>い<ruby><rb>物</rb><rt>もの</rt></ruby>しました。</phrase>
			<phrase lang="en">I did some shopping while taking a walk</phrase>
			<explanation>In this example the act of doing shopping is (far) shorter than the act of talking a walk. When using がてら
			the act to which it is affixed is always the longer "base" event. Usually you will hear the explanation that the shorter,
			more specific event follows the longer base event, but of course - as always in Japanese - what the speaker considers the
			most important comes last, so it is entirely possible to reverse the order provided we keep がてら affixed to the right thing:
			買い物しました。散歩しがてら。 would be perfectly valid (if somewhat colloquial) Japanese.</explanation>
		</example>
	</entry>	

	<entry id="11">
		<particle>から</particle>
		<use>noun/verb phrase suffix</use>
		<description>Denotes point of origin ("start") in terms of time, space, or reasoning.</description>
		<roles>
			<role>from (time, space)</role>
			<role>as of (time)</role>
			<role>after doing (て form)</role>
			<role>because (reasoning)</role>
		</roles>
		<example role="place">
			<phrase lang="jp"><s><ruby><rb>奈良</rb><rt>なら</rt></ruby><p>から</p></s><ruby><rb>来</rb><rt>き</rt></ruby>ました。</phrase>
			<phrase lang="en">We came from Nara.</phrase>
			<explanation>Here the starting point is the city of 奈良 (located in the <ruby><rb>近畿</rb><rt>きんき</rt></ruby> prefecture).</explanation>
		</example>
		<example role="clock-specified time">
			<phrase lang="jp"><s><ruby><rb>十時</rb><rt>じゅうじ</rt></ruby><p>から</p></s><ruby><rb>暇</rb><rt>ひま</rt></ruby>ですよ。</phrase>
			<phrase lang="en">I'll be free as of 10 o' clock.</phrase>
			<explanation>Here the point in time "10 o' clock" is given as the starting point as of when "being available" applies.</explanation>
		</example>
		<example role="event-specified time">
			<phrase lang="jp"><s><ruby><rb>掃除</rb><rt>そうじ</rt></ruby>をして<p>から</p></s>ご<ruby><rb>飯</rb><rt>はん</rt></ruby>を<ruby><rb>作</rb><rt>つく</rt></ruby>ります。</phrase>
			<phrase lang="en">I will made dinner after [I am done with] cleaning.</phrase>
			<explanation>Here the starting point for "making dinner" is set to the undefined moment when the act of "cleaning" is done.
			This uses the verb continuative て form rather than the past tense, as this indicates that the this act has not already been
			performed. If we use the past tense instead, then because the act has already been performed then this cannot act as a future
			moment in time, and will instead be interpreted as a reason, as in the following example.</explanation>
		</example>
		<example role="reason">
			<phrase lang="jp">もう<s><ruby><rb>食</rb><rt>た</rt></ruby>べた<p>から</p></s><ruby><rb>別</rb><rt>べつ</rt></ruby>にお<ruby><rb>腹</rb><rt>なか</rt></ruby>は<ruby><rb>空</rb><rt>す</rt></ruby>いてません。</phrase>
			<phrase lang="en">I already ate, so I'm not particularly hungry.</phrase>
			<explanation>Here the statement "I already ate" is used as argument to back up "I am not particularly hungry".</explanation>
		</example>
	</entry>

	<entry id="12">
		<particle>からして</particle>
		<compound>から+して</compound>
		<use>noun phrase suffix</use>
		<description>A compound of から and して (て form of する). Marks a basis for (a series of) comment(s).</description>
		<roles>
			<role>starting with</role>
		</roles>
		<example role="example">
			<phrase lang="jp"><s><ruby><rb>服</rb><rt>ふく</rt></ruby><p>からして</p></s>、<ruby><rb>彼</rb><rt>かれ</rt></ruby>は<ruby><rb>派手</rb><rt>はで</rt></ruby>な<ruby><rb>男</rb><rt>おとこ</rt></ruby>ですね。</phrase>
			<phrase lang="en">[If we] start with his clothes, [it's clear] he's a pretty flashy guy.</phrase>
			<explanation></explanation>
		</example>
	</entry>

	<entry id="14">
		<particle>かしら</particle>
		<use>sentence ending</use>
		<description>Effeminate particle, equivalent to かな.</description>
		<roles>
			<role>dubitative</role>
		</roles>
		<example role="example">
			<phrase lang="jp"><s><ruby><rb>安</rb><rt>やす</rt></ruby>くて<ruby><rb>買</rb><rt>か</rt></ruby>おう<p>かしら</p></s>。</phrase>
			<phrase lang="en">It's [quite] expensive, I wonder if I should buy it.</phrase>
			<explanation>This is the only truly effeminate particle in Japanese, used exclusively by women, transvestites,
			and particularly feminine gay men.</explanation>
		</example>
	</entry>

	<entry id="15">
		<particle>かよ</particle>
		<compound>か+よ</compound>
		<use>sentence ending</use>
		<description>A compound of か and よ.</description>
		<roles>
			<role>strong question mark</role>
		</roles>
		<example role="example">
			<phrase lang="jp"><s><ruby><rb>何</rb><rt>なん</rt></ruby>で<ruby><rb>連絡</rb><rt>れんらく</rt></ruby>しなかった<p>かよ</p></s>。</phrase>
			<phrase lang="en">Why [the hell] didn't you contact me?</phrase>
			<explanation>The combination of か and よ is an extreme case of stressing, which is reflected in the translation by the
			English expletive "why the hell".</explanation>
		</example>
	</entry>

	<entry id="16">
		<particle>きり</particle>
		<literary>切り</literary>
		<literary>限り</literary>
		<use>noun/verb phrase/case particle</use>
		<description>Restricts a situation to only one case.</description>
		<roles>
			<role>only</role>
			<role>merely</role>
		</roles>
		<contrast id="43">だけ</contrast>
		<see id="17">ぎり</see>
		<!-- change to 二人 -->
		<example role="restiction of quantity">
			<phrase lang="jp"><s><ruby><rb>一人</rb><rt>ひとり</rt></ruby><p>きり</p></s>でその<ruby><rb>仕事</rb><rt>しごと</rt></ruby>をしました。</phrase>
			<phrase lang="en">I did that job on my own.</phrase>
			<explanation>In this use きり is interchangable with だけ, with a nuance difference. The use of きり focusses on
			the fact that only one person did the job (implying there was no one else around to do it), while using でけ focusses on the
			fact that of a group of people only one person did the job.</explanation>
		</example>
		<!-- 祖父は大病を患ったため寝たきりになりました。 -->
		<example role="restriction on action">
			<phrase lang="jp">いすが<ruby><rb>少</rb><rt>すく</rt></ruby>なくて、<s><ruby><rb>立</rb><rt>た</rt></ruby>った<p>きり</p></s><ruby><rb>授業</rb><rt>じゅぎょう</rt></ruby>を<ruby><rb>受</rb><rt>う</rt></ruby>けた。</phrase>
			<!-- change to まま -->
			<phrase lang="en">There were few chairs, so I [sat] through [the entire] class standing.</phrase>
			<explanation>Here the act of "sitting through class" (an unfortunate English expression, which is only marginally related to actual sitting) is restricted to the a case of only being able to do this standing.</explanation>
		</example>		
		<example role="restriction on negative action">
			<phrase lang="jp">ドイツへ<s><ruby><rb>行</rb><rt>い</rt></ruby>った<p>きり</p></s><ruby><rb>帰</rb><rt>かえ</rt></ruby>って<ruby><rb>来</rb><rt>こ</rt></ruby>ない。</phrase>
			<phrase lang="en">After going to Germany he hasn't come back home.</phrase>
			<explanation>Here the action statement "he hasn't come home" has been restricted to applying only to the case of "having gone to Germany".
			This pattern of きり plus a negative verb form is typically translatable as "after ... , ... ".</explanation>
		</example>
	</entry>

	<entry id="17">
		<particle>ぎり</particle>
		<literary>切り</literary>
		<use>noun/verb phrase/case particle</use>
		<description>Voiced version of きり, used mostly in reprimands.</description>
		<see id="16">きり</see>
	</entry>

	<entry id="18">
		<particle>くせに</particle>
		<literary>癖に</literary>
		<compound>くせ+に</compound>
		<use>noun+の/verb phrase suffix</use>
		<description>A combination of "habit" and the affixing particle に. Used to indicate there is a norm from which is being deviated (negative connotation).</description>
		<roles>
			<role>even though</role>
			<role>despite</role>
		</roles>
		<example role="noun phrase example">
			<phrase lang="jp">ただの<s>ガキの<p>くせに</p></s><ruby><rb>偉</rb><rt>えら</rt></ruby>い<ruby><rb>事</rb><rt>こと</rt></ruby>も<ruby><rb>言</rb><rt>い</rt></ruby>えるんですね。</phrase>
			<phrase lang="en">You're just a kid, but you can say some profound things [sometimes] don't you?</phrase>
			<explanation>Normally, kids are not really expected to say profound, so this would definitely be a deviation from the norm.</explanation>
		</example>
		<example role="verb phrase example">
			<phrase lang="jp">いつも<s><ruby><rb>叱</rb><rt>しか</rt></ruby>られる<p>くせに</p></s><ruby><rb>何</rb><rt>なん</rt></ruby>で<ruby><rb>褒</rb><rt>ほ</rt></ruby>めてるんですか。</phrase>
			<phrase lang="en">I'm always being scolded by you, why are you praising me [all of a sudden]?</phrase>
			<explanation>If the norm has been established as "being scolded all the time", then being praised is a clear deviation from this norm.</explanation>
		</example>
	</entry>

	<entry id="19">
		<particle>くらい</particle>
		<literary>位</literary>
		<use>extent suffix</use>
		<description>Marks rough extent in duration or action.</description>
		<contrast id="27">ごろ</contrast>
		<see id="20">ぐらい</see>
		<example role="rough extent of duration">
			<phrase lang="jp"><ruby><rb>一日</rb><rt>いちにち</rt></ruby>に<s><ruby><rb>４時間</rb><rt>よじかん</rt></ruby><p>くらい</p></s><ruby><rb>勉強</rb><rt>べんきょう</rt></ruby>します。</phrase>
			<phrase lang="en">I study roughly four hours a day.</phrase>
			<explanation>In this sentence the exact time statement ４時間, "four hours" is marked as rough estimate instead. Do not confuse
			with with the suffix ごろ, which does almost the same for exact moments in time (clock time), rather than duration.</explanation>
		</example>
		<example role="rough extent of action">
			<phrase lang="jp"><s>それ<p>くらい</p></s><ruby><rb>分</rb><rt>わ</rt></ruby>かっていますけど。</phrase>
			<phrase lang="en">Well, that much I do understand...</phrase>
			<explanation>In this example the word それ, contextually translatable as "that which was just said", is marked as the extend of the speaker's understood matter.</explanation>
		</example>
	</entry>


	<entry id="20">
		<particle>ぐらい</particle>
		<literary>位</literary>
		<use>durational time suffix</use>
		<description>Voiced version of くらい.</description>
		<see id="19">くらい</see>
	</entry>

	<entry id="21">
		<particle>けど</particle>
		<compound>け+ど</compound>
		<use>verb phrase suffix</use>
		<description>Equivalent to けども, using the concessive particle ど instead of ども.</description>
		<see id="23">けども</see>
		<see id="24">けれども</see>
	</entry>

	<entry id="22">
		<particle>けども</particle>
		<compound>け+ども</compound>
		<use>verb phrase suffix</use>
		<description>Equivalent to けれども, formed out of the 已然形 of the classical verb き (which looks at the past) and classical 
		concessive particle ども.</description>
		<see id="24">けれども</see>
	</entry>

	<entry id="23">
		<particle>けれど</particle>
		<compound>けれ+ど</compound>
		<use>verb phrase suffix</use>
		<description>Equivalent to けれども, using the concessive particle ど instead of ども.</description>
		<see id="24">けれども</see>
	</entry>

	<entry id="24">
		<particle>けれども</particle>
		<compound>けれ+ども</compound>
		<use>verb phrase suffix</use>
		<description>Contrastive conjunctive. Can be used in the forms けれども, けども, けれも and けど (following the old adage "the
		longer, the more formal"). This compound comes from the classical verb けり (which takes the present and looks back at it as
		past) in 已然形 suffixed with the classical compound particle ども (a concessive conjunction). From this combination the
		meaning of けれども is fairly immediate. This particle can be used either as conjunctive or interjection.</description>
		<roles>
			<role>however</role>
		</roles>
		<example role="interjection">
			<phrase lang="jp"><s>ジャズもいいと<ruby><rb>思</rb><rt>おも</rt></ruby>う<p>けど</p></s>。</phrase>
			<phrase lang="en">I think jazz [music] is good too, though.</phrase>
			<explanation>This is an example of the interjection use, where it serves as a comment following up something said earlier,
			such as "I really love rock music".</explanation>
		</example>
		<example role="conjunctive">
		
			<phrase lang="jp"><s><ruby><rb>頑固</rb><rt>がんこ</rt></ruby>なやつだ<p>けれど</p></s>、<ruby><rb>弟</rb><rt>おとうと</rt></ruby>ですからかわいくて<ruby><rb>当然</rb><rt>とうぜん</rt></ruby>でしょう。</phrase>
			<phrase lang="en">He's a stubborn guy, but he's [also] my brother, so obviously I love him.</phrase>
			<explanation>In this example we see a normal contrast similar to the English "even though" or "despite".</explanation>
		</example>
	</entry>

	<entry id="140">
		<particle>ご</particle>
		<literary>御</literary>
		<use>noun prefix</use>
		<description>Honorifix prefix. Used (predominantly) for words that have been derived from Chinese or use Chinese readings for their kanji.</description>
		<see id="139">お</see>
		<see id="141">み</see>
		<example role="example">
			<phrase lang="jp"><s><p>ご</p><ruby><rb>立派</rb><rt>りっぱ</rt></ruby></s>な女になられました。</phrase>
			<phrase lang="en">[She] has become a fine woman.</phrase>
			<explanation>The noun adjective 立派 is read using the chinese readings of its kanji, and gets ご rather than お as reading for the honorific prefix.
			(The なられる in this sentence is the honorific form of なる)</explanation>
		</example>
	</entry>

	<entry id="25">
		<particle>こそ</particle>
		<use>noun suffix</use>		
		<description>Places emphasis on, or moves emphasis from something to, the preceding clause.</description>
		<example role="shifting emphasis">
			<phrase lang="jp">A:　あっ、すみません。</phrase>
			<phrase lang="en">Oh dear, excuse me.</phrase>
			<phrase lang="jp">B:　いいえいいえ、<s>こちら<p>こそ</p></s>どうもすみません。</phrase>
			<phrase lang="en">No, no, excuse *me*.</phrase>